config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'pages#index'

  resources :profiles 
  resources :posts# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
end

app/models/profile.rb
class Profile < ApplicationRecord
	belongs_to :user

    has_attached_file :avatar, styles: {thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

    validates :firstname, :lastname, :age, :avatar, presence: true
    validates :age, numericality: { only_integer: true, greater_than_or_equal_to: 18, less_than: 65 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :authenticate_user!
  def new
  	@post = Post.new
  end

  def create
  	@post = current_user.build_post(post_params)
  	if post.save
  		redirect_to root_path
  	else
  		render 'new'
  	end
  end

  def show
  	@post = Post.find_by(id: params[:id])
  end

  def edit
  	@post = Post.find_by(id: params[:id])
  end

  def update
  	@post = Post.find_by(id: params[:id])
    if @post.update(post_params)
  		redirect_to post_path(@post.id)
  	else
  		render 'edit'
  	end
  end

  def destroy
    @post = Post.find_by(id: params[:id])
  	@post.destroy 
  	redirect_to root_path
  end

private 
  def post_params
  	params.require(:post).permit(:post_id, :title, :description, :price)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
before_action :authenticate_user!
  def new
  	@profile = Profile.new
  end

  def create
  	@profile = current_user.build_profile(profile_params)
  	if @profile.save
  		redirect_to root_path
  end

  def show
  	@profile = Profile.find_by(id: params[:id])
  end

  def edit
  	@profile = Profile.find_by(id: params[:id])
  end

  def update
  	@profile = Profile.find_by(id: params[:id])
    if @profile.update(profile_params)
  		redirect_to profile_path(@profile.id)
  	else
  		render 'edit'
  	end
  end

  def destroy
    @profile = Profile.find_by(id: params[:id])
  	@profile.destroy 
  	redirect_to root_path
  end

private 
  def profile_params
  	params.require(:profile).permit(:user_id, :firstname, :lastname, :age, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Doshka</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<% if !user_signed_in? %>
	<%= link_to "Login", user_session_path %>
<% else %>
	<%= link_to "My Profile", profile_path(current_user.id) %> | 
	<%= link_to "Logout", destroy_user_session_path, method: :delete %><br>
	<%= link_to "Add product", posts_path %>
<% end %>

app/views/posts/new.htmal.erb
<%= form_for @post, url: post_path do |f| %>
  Title: <%= f.text_field :title %><br />
  Description: <%= f.text_field :description %><br />
  Price: <%= f.text_field :price %><br />
  <%= f.submit "Post" %>
<% end %>

app/views/posts/show.html.erb
Title: <%= current_user.post.title %><br />
Description: <%= current_user.post.description %><br />
Price: <%= current_user.post.price %><br />

app/views/profiles/edit.html.erb
<%= form_for @profile, url: profile_path(current_user.id) do |f| %>
  Firstname: <%= f.text_field :firstname %><br />
  Lastname: <%= f.text_field :lastname %><br />
  Age: <%= f.text_field :age %><br />
  Avatar: <%= f.file_field :avatar %><br />
  <%= f.submit "Update" %>
<% end %>

app/views/profiles/new.html.erb
<%= form_for @profile, url: profile_path do |f| %>
  Firstname: <%= f.text_field :firstname %><br />
  Lastname: <%= f.text_field :lastname %><br />
  Age: <%= f.text_field :age %><br />
  Avatar: <%= f.file_field :avatar %><br />
  <%= f.submit "Create" %>
<% end %>

app/views/profiles/show.html.erb
Avatar:<%= image_tag current_user.profile.avatar.url(:thumb) %><br />
Firstname: <%= current_user.profile.firstname %><br />
Lastname: <%= current_user.profile.lastname %><br />
Age: <%= current_user.profile.age %><br />
<%= link_to "Edit", edit_profile_path(current_user.id) %><br />